// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKYemZkaJZWG2kvxarG9a17vJEKl0lgPw',
    appId: '1:365758086553:web:829379ecf13a36b1d66708',
    messagingSenderId: '365758086553',
    projectId: 'love-test-2024',
    authDomain: 'love-test-2024.firebaseapp.com',
    storageBucket: 'love-test-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJwD10OryEJlvqdvAoutMkWCH5UUoNiTk',
    appId: '1:365758086553:android:d198a4c731e5fa8bd66708',
    messagingSenderId: '365758086553',
    projectId: 'love-test-2024',
    storageBucket: 'love-test-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAauV-LQHLM3zobCLyCAFFpgNcYX3vnCfE',
    appId: '1:951886145589:ios:b51bbc7e2e96609c39697c',
    messagingSenderId: '951886145589',
    projectId: 'love-test-36c8b',
    storageBucket: 'love-test-36c8b.firebasestorage.app',
    iosBundleId: 'com.miyazakiari.loveTest',
  );
}
